spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/girl?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
#    这里是tomcat的数据库连接池，这个项目里用的是c3p0连接池。
#    tomcat:
#      max-idle: 10
#      max-wait: 100000
#     min-idle: 5
#     initial-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    jedis: # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
      pool:
        max-idle: 500 # 最大空闲连接数
        min-idle: 50 # 最小空闲连接数
        max-wait:  -1s  # 等待可用连接的最大时间，负数为不限制
        max-active: -1 # 最大活跃连接数，负数为不限制

mybatis:
  mybatis_config_file: mybatis-config.xml
  mapper_path: /mapper/**.xml
  entity_package: myggirl.wangpan.domains