spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/girl?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
#    这里是tomcat的数据库连接池，这个项目里用的是c3p0连接池。
#    tomcat:
#      max-idle: 10
#      max-wait: 100000
#     min-idle: 5
#     initial-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0

mybatis:
  mybatis_config_file: mybatis-config.xml
  mapper_path: /mapper/**.xml
  entity_package: myggirl.wangpan.domains